; DefianceRMLoader configuration file. Must be in the same directory as the game executable and the ASI to be read.
; All settings are optional, Delete this file to restore defaults.

[Console]
; Show the mod loader's debug console (0 = Hidden | 1 = Visible)
; WARNING: Closing the console will also close the game so be careful!
ConsoleEnabled=0

[Logging]
; Log every asset request including non-modded ones.
; Very noisy, Recommended for debugging purposes otherwise disable it for normal play once everything works as it affects the game's file loading speed.
VerboseLogging=0

; Log [TRACE] lines for assets that aren't overridden by mods. Requires Verbose Logging to be enabled to have any effect.
LogAllFiles=0

; Mirror all console output to DefianceRMLoader.log in the game folder for debugging purposes. (Doesn't require the console to be enabled)
FileLogEnabled=0

; Log every internal fopen call. (Very noisy; Only for debugging purposes so it's recommended to keep it off during normal play.)
FopenTrace=0
